### ISSUE TITLE
抄袭?

### ISSUE THREAD

**Issue by baoyang23** [19920625lsg/spring-cloud-online-exam#11]
你这是完全复制别人的,一次Commit?你修改的地方呢？不做说明出来?

**Comment by 19920625lsg** [comment]
我README里开头就写清楚了基于谁的项目改地了吧？之前我commits过十几次，我觉得提交记录太乱就重置了master，不会用git就别来github丢人行不？修改的哪些地方你不会用Beyond Compare吗？原来的配置中心和前端启动不起来，我改了四五处，不信自己用BC去和原始项目对比下。

**Comment by baoyang23** [comment]
> 我README里开头就写清楚了基于谁的项目改地了吧？之前我commits过十几次，我觉得提交记录太乱就重置了master，不会用git就别来github丢人行不？修改的哪些地方你不会用Beyond Compare吗？原来的配置中心和前端启动不起来，我改了四五处，不信自己用BC去和原始项目对比下。

你一次commit ， 我去哪儿对比  你提交我修改了什么? 是的。后端是可以启动的，但是你自己测试过http://localhost:8871/exam/druid/index.html这个地址登录权限回跳？如果你基于你这个项目,不去拿原项目,一次commit 是怎么可能看出？

**Comment by baoyang23** [comment]
如果你觉得你这个一次commit;可以在你这个基础上看出你修改的地方，那么请告诉在下是怎么操作，新人，不好意思，请不要急躁。一般看修改都是从commit进行对比。

**Comment by 19920625lsg** [comment]
之前有十几次commit，但是我改地比较乱，所以我就拉了个新分支，删除了原来的master，把分支重置了下改成了新的master。想看提交记录的话你可看下别人早期fork的我的分支。不过这个项目的前端和后面的鉴权原来的作者也没做完，前端还用地AngularJS，不建议用了，我自己在重新写，目前repo还在private阶段。不过原作者新出了一个项目，可以参考下，https://gitee.com/wells2333/spring-microservice-exam

**Comment by baoyang23** [comment]
> 之前有十几次commit，但是我改地比较乱，所以我就拉了个新分支，删除了原来的master，把分支重置了下改成了新的master。想看提交记录的话你可看下别人早期fork的我的分支。不过这个项目的前端和后面的鉴权原来的作者也没做完，前端还用地AngularJS，不建议用了，我自己在重新写，目前repo还在private阶段。不过原作者新出了一个项目，可以参考下，https://gitee.com/wells2333/spring-microservice-exam

是的。是我误解了。多谢。
